### ISSUE TITLE
InvalidArgumentException View [empty] not found.

### ISSUE THREAD

**Issue by nalawi** [shashankNb/laravel-multilevel-drop-down#1]
Just tried your code but got an error:

InvalidArgumentException View [empty] not found.

Thanks

**Comment by shashankNb** [comment]
It seems that there are no any records in your database. Please add some also I forgot to check to disable the menus if there are no menu items in database, I have updated the code. I have also created a seeder called MenuSeeder.php inside database/seeder which you can use to generate dummy menus. Just do php artisan db:seed

**Comment by shashankNb** [comment]
> Just tried your code but got an error:
> 
> InvalidArgumentException View [empty] not found.
> 
> Thanks

It seems that there are no any records in your database. Please add some, also I forgot to check to disable the menus if there are no menu items in database, I have updated the code. I have also created a seeder called MenuSeeder.php inside database/seeder which you can use to generate dummy menus. Just do >> php artisan db:seed
